class AdDisplayInfo {
  String title,
      photoBool,
      country,
      subCountry,
      subSubCategory,
      model,
      username,
      communication,
      docId,
      selectedCategory,
      subCategory,
      commission,
      membership,
      user,
      photoPath;
  int dateDays, dateHours, dateMins;
  AdDisplayInfo(
      {this.title,
      this.docId,
      this.photoPath,
      this.subCountry,
      this.subSubCategory,
      this.country,
      this.model,
      this.username,
      this.user,
      this.photoBool,
      this.selectedCategory,
      this.subCategory,
      this.dateDays,
      this.dateHours,
      this.commission,
      this.membership,
      this.communication,
      this.dateMins});
}
